name: CI - Test PDF Extractor

on:
  push:
    branches:
      - main
      - release/*

jobs:
  test:
    name: Run tests on Node ${{ matrix.node_version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18.x', '20.x']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install, Build, and Test
        run: |
          npm ci
          npm run build --if-present
          npm test
